apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: nexus-platform
  annotations:
    nexus.io/adr: "ADR-014, ADR-018"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: nexus
  source:
    repoURL: https://github.com/koussayx8/nexus-platform.git
    targetRevision: main
    path: platform
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff: { duration: 10s, factor: 2, maxDuration: 3m }
