apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: crossplane-infrastructure

labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/part-of: nexus-platform

resources:
  - namespace.yaml
